### ISSUE TITLE
Missing HID Input Reports on ESP32

### ISSUE THREAD

**Issue by JSnowden33** [bluekitchen/btstack#229] opened 2019-06-09 16:53 UTC
Hi,

I'm working with the BTstack develop branch to interface with Joy-Con controllers, which use Bluetooth HID protocol. I've used the "hid_host_demo" to form a connection, and "l2cap_send()" to send output reports since that is not included in the demo. Output reports work fine - I am able to change the LED output on the controller with them. The "3F" input report is pushed from the Joy-Con whenever a button is pressed or released, and I receive those. However, I am not receiving any other input reports. There should be reports in response to every output report, but I don't get those. I should also be receiving regular reports from the Joy-Con after enabling the full reporting mode, which is shown at the end of the log (the output report directly above "DR pressed" enables 60Hz reporting mode). The report formats and expected responses are all documented [here](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_notes.md) and [here](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_subcommands_notes.md).

Is it possible there is some incompatibility between the Joy-Con and the ESP32 that prevents receiving certain data? Perhaps more L2CAP channels should be opened (there's only one for interrupt and one for control currently)?

Console log:
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5280
ho 0 tail 12 room 4
load:0x40078000,len:10872
ho 0 tail 12 room 4
load:0x40080400,len:6380
entry 0x40080710
I (170) cpu_start: Pro cpu up.
I (170) cpu_start: Application information:
I (171) cpu_start: Project name:     hid_host_demo
I (173) cpu_start: App version:      1
I (178) cpu_start: Compile time:     Jun  2 2019 20:15:20
I (184) cpu_start: ELF file SHA256:  2b170d11d955d1cb...
I (190) cpu_start: ESP-IDF:          v4.0-dev-667-gda13efc17-dirty
I (197) cpu_start: Single core mode
I (201) heap_init: Initializing. RAM available for dynamic allocation:
I (208) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (214) heap_init: At 3FFB7468 len 00000B98 (2 KiB): DRAM
I (220) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (226) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (232) heap_init: At 3FFC7DA0 len 00018260 (96 KiB): DRAM
I (239) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
I (245) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (251) heap_init: At 400908A0 len 0000F760 (61 KiB): IRAM
I (257) cpu_start: Pro cpu start user code
I (52) esp_core_dump_common: Init core dump to UART
E (52) esp_core_dump_common: No core dump partition found!
I (52) cpu_start: Starting scheduler on PRO CPU.
BTstack: setup
I (73) BTDM_INIT: BT controller compile version [484c057]
I (74) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (163) phy: phy_version: 4100, 2a5dd04, Jan 23 2019, 21:00:07, 0, 0
[00:00:00.481] EVT <= 60 01 01
[00:00:00.483] CMD => 03 0C 00
BTstack: execute run loop
[00:00:00.484] EVT <= 6E 00
[00:00:00.484] EVT <= 0E 04 05 03 0C 00
[00:00:00.485] CMD => 01 10 00
[00:00:00.488] EVT <= 0E 0C 05 01 10 00 08 0E 03 08 60 00 0E 03
[00:00:00.494] EVT <= 6E 00
[00:00:00.496] CMD => 14 0C 00
[00:00:00.499] EVT <= 0E FC 05 14 0C 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:00.567] EVT <= 6E 00
[00:00:00.570] CMD => 02 10 00
[00:00:00.573] EVT <= 0E 44 05 02 10 00 BF FF FF 03 CC FF EF FF 3F FF FC 1F F2 0F E8 FE 3F F7 8F FF 1C 00 04 00 61 F7 FF FF 7F 38 C0 FF 7F FF FF 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:00.593] EVT <= 6E 00
[00:00:00.596] CMD => 09 10 00
[00:00:00.599] EVT <= 0E 0A 05 09 10 00 DE 45 9C E3 50 CC
[00:00:00.604] EVT <= 6E 00
[00:00:00.606] CMD => 05 10 00
[00:00:00.609] EVT <= 0E 0B 05 05 10 00 FD 03 FF 09 00 04 00
[00:00:00.615] EVT <= 6E 00
[00:00:00.617] CMD => 03 10 00
[00:00:00.620] EVT <= 0E 0C 05 03 10 00 BF EE CD FE DB FF 7B 87
[00:00:00.626] EVT <= 6E 00
[00:00:00.629] CMD => 33 0C 07 00 04 3C 14 00 0A 00
[00:00:00.633] EVT <= 0E 04 05 33 0C 00
[00:00:00.637] EVT <= 6E 00
[00:00:00.639] CMD => 31 0C 01 03
[00:00:00.643] EVT <= 0E 04 05 31 0C 00
[00:00:00.646] EVT <= 6E 00
[00:00:00.649] CMD => 01 0C 08 FF FF FF FF FF FF FF 3F
[00:00:00.654] EVT <= 0E 04 05 01 0C 00
[00:00:00.657] EVT <= 6E 00
[00:00:00.660] CMD => 56 0C 01 01
[00:00:00.663] EVT <= 0E 04 05 56 0C 00
[00:00:00.667] EVT <= 6E 00
[00:00:00.669] CMD => 18 0C 02 00 60
[00:00:00.673] EVT <= 0E 04 05 18 0C 00
[00:00:00.676] EVT <= 6E 00
[00:00:00.679] CMD => 0F 08 02 00 00
[00:00:00.683] EVT <= 0E 04 05 0F 08 00
[00:00:00.686] EVT <= 6E 00
[00:00:00.689] CMD => 24 0C 03 0C 02 7A
[00:00:00.692] EVT <= 0E 04 05 24 0C 00
[00:00:00.696] EVT <= 6E 00
[00:00:00.699] CMD => 13 0C F8 42 54 73 74 61 63 6B 20 43 43 3A 35 30 3A 45 33 3A 39 43 3A 34 35 3A 44 45 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:00.766] EVT <= 0E 04 05 13 0C 00
[00:00:00.770] EVT <= 6E 00
[00:00:00.772] CMD => 52 0C F1 00 1A 09 42 54 73 74 61 63 6B 20 43 43 3A 35 30 3A 45 33 3A 39 43 3A 34 35 3A 44 45 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:00.838] EVT <= 0E 04 05 52 0C 00
[00:00:00.842] EVT <= 6E 00
[00:00:00.844] CMD => 45 0C 01 00
[00:00:00.847] EVT <= 0E 04 05 45 0C 00
[00:00:00.851] EVT <= 6E 00
[00:00:00.854] CMD => 1A 0C 01 00
[00:00:00.857] EVT <= 0E 04 05 1A 0C 00
[00:00:00.860] EVT <= 66 01 00
[00:00:00.863] EVT <= 6E 00
[00:00:00.866] CMD => 2F 0C 01 01
[00:00:00.869] EVT <= 0E 04 05 2F 0C 00
[00:00:00.873] EVT <= 6E 00
[00:00:00.875] CMD => 5B 0C 01 01
[00:00:00.878] EVT <= 0E 04 05 5B 0C 00
[00:00:00.882] EVT <= 6E 00
[00:00:00.885] CMD => 02 20 00
[00:00:00.887] EVT <= 0E 07 05 02 20 00 FB 00 0A
[00:00:00.892] EVT <= 6E 00
[00:00:00.894] CMD => 6D 0C 02 01 00
[00:00:00.898] EVT <= 0E 04 05 6D 0C 00
[00:00:00.901] EVT <= 6E 00
[00:00:00.904] CMD => 01 20 08 FF 09 08 00 00 00 00 00
[00:00:00.909] EVT <= 0E 04 05 01 20 00
[00:00:00.913] EVT <= 6E 00
[00:00:00.915] CMD => 0F 20 00
[00:00:00.918] EVT <= 0E 05 05 0F 20 00 0C
[00:00:00.922] EVT <= 6E 00
[00:00:00.925] CMD => 0B 20 07 01 E0 01 30 00 00 00
[00:00:00.929] EVT <= 0E 04 05 0B 20 00
[00:00:00.933] EVT <= 60 01 02
BTstack up and running at CC:50:E3:9C:45:DE
Start SDP HID query for remote HID Device.
[00:00:00.944] EVT <= 6E 00
[00:00:00.946] CMD => 05 04 0D 65 47 2E 1E 52 5C 18 CC 00 00 00 00 01
[00:00:00.953] EVT <= 0F 04 00 05 05 04
[00:00:00.956] EVT <= 6E 00
[00:00:03.967] EVT <= 03 0B 00 80 00 65 47 2E 1E 52 5C 01 00
[00:00:03.968] EVT <= 61 01 01
[00:00:03.968] CMD => 1B 04 02 80 00
[00:00:03.969] EVT <= 1B 03 80 00 05
[00:00:03.971] EVT <= 0F 04 00 05 1B 04
[00:00:03.974] EVT <= 0B 0B 00 80 00 BF F8 CB FE CB EF 7B 87
[00:00:03.980] EVT <= 6E 00
[00:00:03.983] ACL => 80 00 0C 00 08 00 01 00 02 01 04 00 01 00 40 00
[00:00:03.989] EVT <= 6E 00
[00:00:03.992] EVT <= 13 05 01 80 00 01 00
[00:00:03.995] ACL <= 80 20 10 00 0C 00 01 00 03 01 08 00 40 00 40 00 00 00 00 00
[00:00:04.003] ACL => 80 00 10 00 0C 00 01 00 04 02 08 00 40 00 00 00 01 02 9B 06
[00:00:04.010] ACL <= 80 20 10 00 0C 00 01 00 04 02 08 00 40 00 00 00 01 02 30 00
[00:00:04.017] EVT <= 13 05 01 80 00 01 00
[00:00:04.021] ACL <= 80 20 12 00 0E 00 01 00 05 02 0A 00 40 00 00 00 00 00 01 02 FD 03
[00:00:04.029] EVT <= 6E 00
[00:00:04.031] ACL => 80 00 12 00 0E 00 01 00 05 02 0A 00 40 00 00 00 00 00 01 02 30 00
[00:00:04.039] EVT <= 70 18 00 65 47 2E 1E 52 5C 80 00 01 00 40 00 40 00 9B 06 30 00 00 00 00 00 00
[00:00:04.048] EVT <= 13 05 01 80 00 01 00
[00:00:04.052] EVT <= 6E 00
[00:00:04.055] EVT <= 78 02 40 00
[00:00:04.058] ACL => 80 00 18 00 14 00 40 00 06 00 01 00 0F 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 00
[00:00:04.067] EVT <= 6E 00
[00:00:04.070] CMD => 35 0C 05 01 80 00 03 00
[00:00:04.074] EVT <= 13 05 01 80 00 01 00
[00:00:04.078] ACL <= 80 20 34 00 30 00 40 00 07 00 01 00 2B 00 26 36 01 78 36 01 75 09 00 01 35 03 19 11 24 09 00 04 35 0D 35 06 19 01 00 09 00 11 35 03 19 00 11 09 00 05 35 03 19 02 00 26
HID Control PSM: 0x0011
[00:00:04.097] EVT <= 6E 00
[00:00:04.099] EVT <= 78 02 40 00
[00:00:04.102] ACL => 80 00 1A 00 16 00 40 00 06 00 02 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 00 26
[00:00:04.112] EVT <= 6E 00
[00:00:04.115] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.119] EVT <= 6E 00
[00:00:04.168] EVT <= 13 05 01 80 00 01 00
[00:00:04.245] ACL <= 80 20 34 00 30 00 40 00 07 00 02 00 2B 00 26 10 02 09 00 06 35 09 09 65 6E 09 00 6A 09 01 00 09 00 09 35 08 35 06 19 11 24 09 01 01 09 00 0D 35 0F 35 0D 35 06 02 00 4C
[00:00:04.251] EVT <= 78 02 40 00
[00:00:04.254] ACL => 80 00 1A 00 16 00 40 00 06 00 03 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 00 4C
[00:00:04.264] EVT <= 6E 00
[00:00:04.267] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.271] EVT <= 6E 00
[00:00:04.310] EVT <= 13 05 01 80 00 01 00
[00:00:04.313] ACL <= 80 20 34 00 30 00 40 00 07 00 03 00 2B 00 26 19 01 00 09 00 13 35 03 19 00 11 09 01 00 25 10 57 69 72 65 6C 65 73 73 20 47 61 6D 65 70 61 64 09 01 01 25 07 47 02 00 72
HID Interrupt PSM: 0x0013
[00:00:04.322] EVT <= 78 02 40 00
[00:00:04.325] ACL => 80 00 1A 00 16 00 40 00 06 00 04 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 00 72
[00:00:04.335] EVT <= 6E 00
[00:00:04.338] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.342] EVT <= 6E 00
[00:00:04.378] EVT <= 13 05 01 80 00 01 00
[00:00:04.380] ACL <= 80 20 34 00 30 00 40 00 07 00 04 00 2B 00 26 61 6D 65 70 61 64 09 01 02 25 08 4E 69 6E 74 65 6E 64 6F 09 02 01 09 01 11 09 02 02 08 08 09 02 03 08 21 09 02 04 02 00 98
[00:00:04.388] EVT <= 78 02 40 00
[00:00:04.390] ACL => 80 00 1A 00 16 00 40 00 06 00 05 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 00 98
[00:00:04.401] EVT <= 6E 00
[00:00:04.403] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.407] EVT <= 6E 00
[00:00:04.445] EVT <= 13 05 01 80 00 01 00
[00:00:04.448] ACL <= 80 20 34 00 30 00 40 00 07 00 05 00 2B 00 26 28 01 09 02 05 28 01 09 02 06 35 B0 35 AE 08 22 25 AA 05 01 09 05 A1 01 06 01 FF 85 21 09 21 75 08 95 30 81 02 85 02 00 BE
[00:00:04.455] EVT <= 78 02 40 00
[00:00:04.458] ACL => 80 00 1A 00 16 00 40 00 06 00 06 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 00 BE
[00:00:04.468] EVT <= 6E 00
[00:00:04.470] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.475] EVT <= 6E 00
[00:00:04.513] EVT <= 13 05 01 80 00 01 00
[00:00:04.515] ACL <= 80 20 34 00 30 00 40 00 07 00 06 00 2B 00 26 30 09 30 75 08 95 30 81 02 85 31 09 31 75 08 96 69 01 81 02 85 32 09 32 75 08 96 69 01 81 02 85 33 09 33 75 08 96 02 00 E4
[00:00:04.523] EVT <= 78 02 40 00
[00:00:04.526] ACL => 80 00 1A 00 16 00 40 00 06 00 07 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 00 E4
[00:00:04.536] EVT <= 6E 00
[00:00:04.538] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.542] EVT <= 6E 00
[00:00:04.580] EVT <= 13 05 01 80 00 01 00
[00:00:04.583] ACL <= 80 20 34 00 30 00 40 00 07 00 07 00 2B 00 26 69 01 81 02 85 3F 05 09 19 01 29 10 15 00 25 01 75 01 95 10 81 02 05 01 09 39 15 00 25 07 75 04 95 01 81 42 05 09 02 01 0A
[00:00:04.590] EVT <= 78 02 40 00
[00:00:04.593] ACL => 80 00 1A 00 16 00 40 00 06 00 08 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 01 0A
[00:00:04.603] EVT <= 6E 00
[00:00:04.605] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.610] EVT <= 6E 00
[00:00:04.648] EVT <= 13 05 01 80 00 01 00
[00:00:04.650] ACL <= 80 20 34 00 30 00 40 00 07 00 08 00 2B 00 26 75 04 95 01 81 01 05 01 09 30 09 31 09 33 09 34 16 00 00 27 FF FF 00 00 75 10 95 04 81 02 06 01 FF 85 01 09 01 75 02 01 30
[00:00:04.658] EVT <= 78 02 40 00
[00:00:04.660] ACL => 80 00 1A 00 16 00 40 00 06 00 09 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 01 30
[00:00:04.671] EVT <= 6E 00
[00:00:04.673] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.677] EVT <= 6E 00
[00:00:04.715] EVT <= 13 05 01 80 00 01 00
[00:00:04.718] ACL <= 80 20 34 00 30 00 40 00 07 00 09 00 2B 00 26 08 95 30 91 02 85 10 09 10 75 08 95 30 91 02 85 11 09 11 75 08 95 30 91 02 85 12 09 12 75 08 95 30 91 02 C0 09 02 02 01 56
HID Descriptor:
05 01 09 05 A1 01 06 01 FF 85 21 09 21 75 08 95 30 81 02 85 30 09 30 75 08 95 30 81 02 85 31 09 31 75 08 96 69 01 81 02 85 32 09 32 75 08 96 69 01 81 02 85 33 09 33 75 08 96 69 01 81 02 85 3F 05 09 19 01 29 10 15 00 25 01 75 01 95 10 81 02 05 01 09 39 15 00 25 07 75 04 95 01 81 42 05 09 75 04 95 01 81 01 05 01 09 30 09 31 09 33 09 34 16 00 00 27 FF FF 00 00 75 10 95 04 81 02 06 01 FF 85 01 09 01 75 08 95 30 91 02 85 10 09 10 75 08 95 30 91 02 85 11 09 11 75 08 95 30 91 02 85 12 09 12 75 08 95 30 91 02 C0
[00:00:04.771] EVT <= 78 02 40 00
[00:00:04.774] ACL => 80 00 1A 00 16 00 40 00 06 00 0A 00 11 35 03 19 11 24 06 9B 35 05 0A 00 01 FF FF 02 01 56
[00:00:04.784] EVT <= 6E 00
[00:00:04.786] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.791] EVT <= 13 05 01 80 00 01 00
[00:00:04.794] EVT <= 6E 00
[00:00:04.864] ACL <= 80 20 31 00 2D 00 40 00 07 00 0A 00 28 00 25 07 35 08 35 06 09 04 09 09 01 00 09 02 09 28 01 09 02 0A 28 01 09 02 0C 09 0C 80 09 02 0D 28 00 09 02 0E 28 00 00
[00:00:04.869] ACL => 80 00 0C 00 08 00 01 00 06 03 04 00 40 00 40 00
[00:00:04.876] EVT <= 6E 00
[00:00:04.878] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.882] EVT <= 6E 00
[00:00:04.930] EVT <= 13 05 01 80 00 01 00
[00:00:04.932] ACL <= 80 20 0C 00 08 00 01 00 07 03 04 00 40 00 40 00
[00:00:04.933] EVT <= 71 02 40 00
Setup HID device
[00:00:04.934] CMD => 35 0C 05 01 80 00 01 00
[00:00:04.938] EVT <= 6E 00
[00:00:04.941] CMD => 11 04 02 80 00
[00:00:04.945] EVT <= 0F 04 00 05 11 04
[00:00:04.948] EVT <= 17 06 65 47 2E 1E 52 5C
[00:00:04.952] EVT <= 6E 00
[00:00:04.956] CMD => 0B 04 16 65 47 2E 1E 52 5C 1F AC E3 CE 5A FB 5D 61 A9 94 8B C8 49 DF D4 C0
[00:00:04.964] EVT <= 0E 0A 05 0B 04 00 65 47 2E 1E 52 5C
[00:00:04.969] EVT <= 6E 00
[00:00:05.078] EVT <= 06 03 00 80 00
[00:00:05.079] CMD => 13 04 03 80 00 01
[00:00:05.080] EVT <= 0F 04 00 05 13 04
[00:00:05.080] EVT <= 6E 00
[00:00:05.295] EVT <= 08 04 00 80 00 01
[00:00:05.296] EVT <= E0 03 80 00 02
[00:00:05.296] ACL => 80 00 0C 00 08 00 01 00 02 04 04 00 11 00 41 00
[00:00:05.298] EVT <= 6E 00
[00:00:05.364] EVT <= 13 05 01 80 00 01 00
[00:00:05.365] ACL <= 80 20 10 00 0C 00 01 00 03 04 08 00 41 00 41 00 01 00 00 00
[00:00:05.367] CMD => 35 0C 05 01 80 00 01 00
[00:00:05.369] EVT <= 6E 00
[00:00:05.729] EVT <= 30 03 00 80 00
[00:00:05.808] ACL <= 80 20 10 00 0C 00 01 00 03 04 08 00 41 00 41 00 00 00 00 00
[00:00:05.809] ACL => 80 00 10 00 0C 00 01 00 04 05 08 00 41 00 00 00 01 02 30 00
[00:00:05.812] EVT <= 6E 00
[00:00:05.814] CMD => 35 0C 05 01 80 00 01 00
[00:00:05.818] EVT <= 6E 00
[00:00:05.873] EVT <= 13 05 01 80 00 01 00
[00:00:05.874] ACL <= 80 20 10 00 0C 00 01 00 04 03 08 00 41 00 00 00 01 02 20 03
[00:00:05.876] ACL => 80 00 12 00 0E 00 01 00 05 03 0A 00 41 00 00 00 00 00 01 02 30 00
[00:00:05.881] ACL <= 80 20 12 00 0E 00 01 00 05 05 0A 00 41 00 00 00 00 00 01 02 30 00
[00:00:05.889] EVT <= 70 18 00 65 47 2E 1E 52 5C 80 00 11 00 41 00 41 00 30 00 20 03 00 00 00 00 00
[00:00:05.898] EVT <= E0 03 80 00 02
[00:00:05.901] EVT <= 6E 00
[00:00:05.903] ACL => 80 00 0C 00 08 00 01 00 02 06 04 00 13 00 42 00
[00:00:05.910] EVT <= 6E 00
[00:00:05.912] CMD => 35 0C 05 01 80 00 02 00
[00:00:05.917] EVT <= 6E 00
[00:00:05.943] EVT <= 13 05 01 80 00 01 00
[00:00:05.944] EVT <= 13 05 01 80 00 01 00
[00:00:06.088] ACL <= 80 20 10 00 0C 00 01 00 03 06 08 00 42 00 42 00 01 00 00 00
[00:00:06.089] CMD => 35 0C 05 01 80 00 01 00
[00:00:06.090] EVT <= 6E 00
[00:00:06.304] EVT <= 30 03 00 80 00
[00:00:06.383] ACL <= 80 20 10 00 0C 00 01 00 03 06 08 00 42 00 42 00 00 00 00 00
[00:00:06.384] ACL => 80 00 10 00 0C 00 01 00 04 07 08 00 42 00 00 00 01 02 30 00
[00:00:06.387] EVT <= 6E 00
[00:00:06.389] CMD => 35 0C 05 01 80 00 01 00
[00:00:06.393] EVT <= 6E 00
[00:00:06.448] EVT <= 13 05 01 80 00 01 00
[00:00:06.449] ACL <= 80 20 10 00 0C 00 01 00 04 04 08 00 42 00 00 00 01 02 20 03
[00:00:06.451] ACL => 80 00 12 00 0E 00 01 00 05 04 0A 00 42 00 00 00 00 00 01 02 30 00
[00:00:06.456] ACL <= 80 20 12 00 0E 00 01 00 05 07 0A 00 42 00 00 00 00 00 01 02 30 00
[00:00:06.464] EVT <= 70 18 00 65 47 2E 1E 52 5C 80 00 13 00 42 00 42 00 30 00 20 03 00 00 00 00 00
HID Connection established
Output report packet: A2 01 00 00 00 00 00 00 00 00 00 30 81
[00:00:06.480] EVT <= 6E 00
[00:00:06.483] EVT <= 78 02 42 00
[00:00:06.486] ACL => 80 00 11 00 0D 00 42 00 A2 01 00 00 00 00 00 00 00 00 00 30 81
[00:00:06.494] EVT <= 6E 00
[00:00:06.496] CMD => 35 0C 05 01 80 00 02 00
[00:00:06.500] EVT <= 6E 00
[00:00:06.518] EVT <= 13 05 01 80 00 01 00
[00:00:06.519] EVT <= 13 05 01 80 00 01 00
[00:00:06.597] ACL <= 80 20 11 00 0D 00 42 00 A1 3F 00 00 05 00 80 00 80 00 80 00 80
HID Data: A1 3F 00 00 05 00 80 00 80 00 80 00 80
[00:00:06.599] CMD => 35 0C 05 01 80 00 01 00
[00:00:06.602] EVT <= 6E 00
[00:00:06.663] ACL <= 80 20 11 00 0D 00 42 00 A1 3F 00 00 08 00 80 00 80 00 80 00 80
HID Data: A1 3F 00 00 08 00 80 00 80 00 80 00 80
[00:00:06.665] CMD => 35 0C 05 01 80 00 01 00
[00:00:06.668] EVT <= 6E 00
[00:00:10.514] ACL <= 80 20 11 00 0D 00 42 00 A1 3F 08 00 08 00 80 00 80 00 80 00 80
HID Data: A1 3F 08 00 08 00 80 00 80 00 80 00 80
[00:00:10.516] CMD => 35 0C 05 01 80 00 01 00
Output report packet: A2 01 01 00 00 00 00 00 00 00 00 03 30
DR pressed
[00:00:10.526] EVT <= 6E 00
[00:00:10.529] EVT <= 78 02 42 00
[00:00:10.532] ACL => 80 00 11 00 0D 00 42 00 A2 01 01 00 00 00 00 00 00 00 00 03 30
[00:00:10.540] EVT <= 6E 00
[00:00:10.543] EVT <= 13 05 01 80 00 01 00
```

**Comment by mringwal** [comment] 2019-06-10 16:35
hi. All ACL packets are created equal - if you receive one, you'll receive all of them.
There are 2 channels for HID, Interrupt and Control and the example connects both. 

Do you see the response to the HID Output packets in the HCI log?

**Comment by JSnowden33** [comment] 2019-06-10 22:03
The response packets are not present in any of the logs I'm getting. I can see "LOG -- hci.c.649: hci_send_acl_packet_fragments entered" and so on for outgoing data, but no logs for incoming data other than ACL logs.

I am looking at a USB dump of a Bluetooth transmitter connected to a PC, which allows a Joy-Con to interface with some other open source Joy-Con software. It looks like every output report from this PC program includes padding to make the message 50 bytes long, so I tried doing this as well, but it doesn't change anything. Even when I follow the exact set of output reports use in this example, I should be getting a 50-byte response beginning with "A1 21 ... " in the ACL data, but nothing ever shows up.

USB capture (ACL data is in the second-to-the-right column):
![USB_Joy-Con_Capture](https://user-images.githubusercontent.com/34112118/59229870-ad9d1e80-8ba9-11e9-8df8-5861a3621b9a.PNG)

ESP32 log:
```
HID Connection established
Output report packet: A2 01 00 00 00 00 00 00 00 00 00 03 3F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.166] EVT <= 6E 00
[00:00:04.168] EVT <= 78 02 42 00
[00:00:04.171] ACL => 80 00 36 00 32 00 42 00 A2 01 00 00 00 00 00 00 00 00 00 03 3F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.189] EVT <= 13 05 01 80 00 01 00
Output report packet: A2 01 01 00 00 00 00 00 00 00 00 30 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.246] EVT <= 6E 00
[00:00:04.248] EVT <= 78 02 42 00
[00:00:04.251] ACL => 80 00 36 00 32 00 42 00 A2 01 01 00 00 00 00 00 00 00 00 30 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.269] ACL <= 80 20 11 00 0D 00 42 00 A1 3F 00 00 05 00 80 00 80 00 80 00 80
HID Data: A1 3F 00 00 05 00 80 00 80 00 80 00 80
[00:00:04.281] EVT <= 13 05 01 80 00 01 00
[00:00:04.284] EVT <= 13 05 01 80 00 01 00
[00:00:04.288] ACL <= 80 20 11 00 0D 00 42 00 A1 3F 00 00 08 00 80 00 80 00 80 00 80
HID Data: A1 3F 00 00 08 00 80 00 80 00 80 00 80
Output report packet: A2 01 02 00 00 00 00 00 00 00 00 10 01 60 00 00 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.354] EVT <= 6E 00
[00:00:04.356] EVT <= 78 02 42 00
[00:00:04.359] ACL => 80 00 36 00 32 00 42 00 A2 01 02 00 00 00 00 00 00 00 00 10 01 60 00 00 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Output report packet: A2 01 03 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.431] EVT <= 6E 00
[00:00:04.433] EVT <= 78 02 42 00
[00:00:04.436] ACL => 80 00 36 00 32 00 42 00 A2 01 03 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[00:00:04.454] EVT <= 13 05 01 80 00 01 00
[00:00:04.457] EVT <= 13 05 01 80 00 01 00
[00:00:04.461] EVT <= 6E 00
[00:00:04.464] CMD => 35 0C 05 01 80 00 04 00
[00:00:04.468] EVT <= 6E 00
```

**Comment by mringwal** [comment] 2019-06-11 06:53
Hi. If you like, you can run the code on Windows using the port/windows-winusb to better be able to compare your logs - although you are already comparing ACL packets.

If you like, please post on the BTstack developer mailing list (google group), as I'm probably the only one that reads all issues.

As this is not a bug in BTstack (at least I don't see why), I'm closing this. If BTstack should happen to fail to deliver data to the application, please file a new issue reporting that.

**Closed by mringwal** 2019-06-11 06:53 UTC
